"""auto update

Revision ID: 904d72fe5425
Revises: 
Create Date: 2026-07-04 02:07:21.679129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904d72fe5425'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chronicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('sc_snapshot_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronicles_id'), 'chronicles', ['id'], unique=False)
    op.create_table('diplo_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('from_nation', sa.String(), nullable=False),
    sa.Column('to_nation', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diplo_messages_id'), 'diplo_messages', ['id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provinces_json', sa.String(), nullable=True),
    sa.Column('units_json', sa.String(), nullable=True),
    sa.Column('sc_json', sa.String(), nullable=True),
    sa.Column('nations_json', sa.String(), nullable=True),
    sa.Column('last_orders_json', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_table('nation_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('nation_id', sa.String(), nullable=False),
    sa.Column('nation_name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=True),
    sa.Column('skills_md', sa.String(), nullable=True),
    sa.Column('memory', sa.String(), nullable=True),
    sa.Column('annual_advice', sa.String(), nullable=True),
    sa.Column('aggression', sa.Integer(), nullable=True),
    sa.Column('loyalty', sa.Integer(), nullable=True),
    sa.Column('cunning', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nation_agents_id'), 'nation_agents', ['id'], unique=False)
    op.create_table('war_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_war_reports_id'), 'war_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_war_reports_id'), table_name='war_reports')
    op.drop_table('war_reports')
    op.drop_index(op.f('ix_nation_agents_id'), table_name='nation_agents')
    op.drop_table('nation_agents')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_diplo_messages_id'), table_name='diplo_messages')
    op.drop_table('diplo_messages')
    op.drop_index(op.f('ix_chronicles_id'), table_name='chronicles')
    op.drop_table('chronicles')
    # ### end Alembic commands ###